[package]
name = "zed-moonbit"
version = "0.2.0"
edition = "2021"
authors = [
  "Lorenzo Pirro <lorenzopirro1@gmail.com>",
  "He Linming <hlm52pk@163.com>",
]
description = "MoonBit language support for the Zed editor"
repository = "https://github.com/quirk-lab/zed-moonbit"
readme = "README.md"
license = "MIT"
keywords = ["zed", "moonbit", "language-server", "tree-sitter"]
categories = ["development-tools"]

[dependencies]
zed_extension_api = "0.1.0"

[lib]
crate-type = ["cdylib"]