id = "moonbit"
name = "MoonBit"
version = "0.1.7"
schema_version = 1
authors = ["Lorenzo Pirro <lorenzopirro1@gmail.com>"]
description = "MoonBit language support for Zed Editor. High-contrast premium aesthetics and LSP."
repository = "https://github.com/quirk-lab/zed-moonbit"
license = "MIT"

[grammars.moonbit]
repository = "https://github.com/moonbitlang/tree-sitter-moonbit"
rev = "5435c307c6cf2ef0d508a99047b06f35a4308444"

[language_servers.moonbit]
name = "MoonBit LSP"
languages = ["MoonBit"]
