id = "moonbit"
name = "MoonBit"
version = "0.1.6"
schema_version = 1
authors = ["Lorenzo Pirro <lorenzopirro1@gmail.com>"]
description = "MoonBit language support for Zed Editor. High-contrast premium aesthetics and LSP."
repository = "https://github.com/quirk-lab/zed-moonbit"
license = "MIT"

[grammars.moonbit]
repository = "https://github.com/moonbitlang/tree-sitter-moonbit"
rev = "c76eb43a7ea35de24eec13dee1fe22fadb2533d7"

[language_servers.moonbit-lsp]
name = "MoonBit Language Server"
languages = ["MoonBit"]
