id = "moonbit"
name = "MoonBit"
description = "MoonBit support."
version = "0.1.0"
schema_version = 1
authors = [
    "MrHeer <hlm52pk@163.com>",
    "thomaszdxsn <thomaszdxsn@icloud.com>",
]
repository = "https://github.com/quirk-lab/zed-moonbit"

[language_servers.moonbit]
name = "MoonBit LSP"
language = "MoonBit"
languages = ["MoonBit"]

[grammars.moonbit]
repository = "https://github.com/moonbitlang/tree-sitter-moonbit"
commit = "290094725390a4e5f4fdb0524d1be037016890ba"
